modifiers:
  svg_icons:
    - ph-dt-acompass
    - ph-dt-address-book
    - ph-dt-agorist
    - ph-dt-alien
    - ph-dt-align-left-simple
    - ph-dt-amazon-logo
    - ph-dt-anchor
    - ph-dt-android-logo
    - ph-dt-anon
    - ph-dt-anonist
    - ph-dt-apple-logo
    - ph-dt-archive
    - ph-dt-arrow-arc-left
    - ph-dt-arrow-circle-down
    - ph-dt-arrow-circle-right
    - ph-dt-arrow-clockwise
    - ph-dt-arrow-counter-clockwise
    - ph-dt-arrow-down
    - ph-dt-arrow-fat-lines-down
    - ph-dt-arrow-fat-lines-left
    - ph-dt-arrow-fat-lines-right
    - ph-dt-arrow-fat-lines-up
    - ph-dt-arrow-left
    - ph-dt-arrow-right
    - ph-dt-arrows-clockwise
    - ph-dt-arrows-horizontal
    - ph-dt-arrows-in
    - ph-dt-arrows-in-simple
    - ph-dt-arrows-left-right
    - ph-dt-arrows-out-simple
    - ph-dt-arrow-square-out
    - ph-dt-arrows-vertical
    - ph-dt-arrow-up
    - ph-dt-article
    - ph-dt-asterisk
    - ph-dt-at
    - ph-dt-avocado
    - ph-dt-bed
    - ph-dt-beer
    - ph-dt-bell
    - ph-dt-bell-slash
    - ph-dt-bookmark
    - ph-dt-bookmarks
    - ph-dt-book-open-text
    - ph-dt-briefcase
    - ph-dt-btc
    - ph-dt-bug-beetle
    - ph-dt-bulb
    - ph-dt-cake
    - ph-dt-calendar-blank
    - ph-dt-calendar-plus
    - ph-dt-caret-circle-down
    - ph-dt-caret-circle-left
    - ph-dt-caret-circle-right
    - ph-dt-caret-circle-up
    - ph-dt-caret-double-down
    - ph-dt-caret-double-left
    - ph-dt-caret-double-right
    - ph-dt-caret-double-up
    - ph-dt-caret-down
    - ph-dt-caret-left
    - ph-dt-caret-right
    - ph-dt-caret-up
    - ph-dt-categories
    - ph-dt-certificate
    - ph-dt-chart-at
    - ph-dt-chart-bar
    - ph-dt-chart-line
    - ph-dt-chart-line-down
    - ph-dt-chart-line-up
    - ph-dt-chart-pie
    - ph-dt-chart-scatter
    - ph-dt-chat-centered
    - ph-dt-chat-centered-dots
    - ph-dt-chat-circle
    - ph-dt-chat-dots
    - ph-dt-chats-circle
    - ph-dt-check
    - ph-dt-check-circle
    - ph-dt-check-fat
    - ph-dt-check-square
    - ph-dt-cheers
    - ph-dt-circle
    - ph-dt-circle-half
    - ph-dt-circles-three
    - ph-dt-clipboard
    - ph-dt-clock
    - ph-dt-clock-counter-clockwise
    - ph-dt-cloud-arrow-up
    - ph-dt-code
    - ph-dt-columns
    - ph-dt-copy
    - ph-dt-copyleft
    - ph-dt-copyright
    - ph-dt-crosshair
    - ph-dt-crown-simple
    - ph-dt-cube
    - ph-dt-desktop
    - ph-dt-detective
    - ph-dt-dev
    - ph-dt-device-mobile
    - ph-dt-devices
    - ph-dt-diamond
    - ph-dt-discord-logo
    - ph-dt-dots-three-outline
    - ph-dt-dots-three-outline-vertical
    - ph-dt-download
    - ph-dt-envelope
    - ph-dt-envelope-simple
    - ph-dt-equalizer
    - ph-dt-eth
    - ph-dt-eye
    - ph-dt-eyeglasses
    - ph-dt-eyes
    - ph-dt-eye-slash
    - ph-dt-facebook-logo
    - ph-dt-fast-forward
    - ph-dt-fediverse
    - ph-dt-file
    - ph-dt-file-archive
    - ph-dt-file-audio
    - ph-dt-file-code
    - ph-dt-file-image
    - ph-dt-file-md
    - ph-dt-files
    - ph-dt-file-text
    - ph-dt-file-video
    - ph-dt-flag
    - ph-dt-flask
    - ph-dt-floppy
    - ph-dt-folder
    - ph-dt-folder-notch-open
    - ph-dt-folder-simple-star
    - ph-dt-funnel
    - ph-dt-game
    - ph-dt-gear
    - ph-dt-gear-fine
    - ph-dt-ghost
    - ph-dt-gif
    - ph-dt-gift
    - ph-dt-git-branch
    - ph-dt-github-logo
    - ph-dt-globe
    - ph-dt-globe-hemisphere-west
    - ph-dt-google-chrome-logo
    - ph-dt-graduate
    - ph-dt-grid-four
    - ph-dt-hand-coins
    - ph-dt-hand-down
    - ph-dt-hand-heart
    - ph-dt-handshake
    - ph-dt-hand-up
    - ph-dt-hand-waving
    - ph-dt-heart
    - ph-dt-heartbeat
    - ph-dt-hourglass-high
    - ph-dt-hourglass-low
    - ph-dt-hourglass-medium
    - ph-dt-house
    - ph-dt-identification-card
    - ph-dt-ikigai
    - ph-dt-image
    - ph-dt-info
    - ph-dt-instagram-logo
    - ph-dt-kanban
    - ph-dt-key
    - ph-dt-keyboard
    - ph-dt-lifebuoy
    - ph-dt-lightning
    - ph-dt-link-break
    - ph-dt-link-simple
    - ph-dt-link-simple-horizontal
    - ph-dt-linux-logo
    - ph-dt-list
    - ph-dt-list-bullets
    - ph-dt-list-checks
    - ph-dt-list-dashes
    - ph-dt-list-hearth
    - ph-dt-list-numbers
    - ph-dt-lists
    - ph-dt-lock-key-open
    - ph-dt-lock-open
    - ph-dt-lounge
    - ph-dt-magic-wand
    - ph-dt-magnifying-glass
    - ph-dt-map-pin
    - ph-dt-markdown
    - ph-dt-medal
    - ph-dt-microphone
    - ph-dt-microphone-slash
    - ph-dt-minus
    - ph-dt-minus-circle
    - ph-dt-moon
    - ph-dt-nauta
    - ph-dt-notebook
    - ph-dt-notepad
    - ph-dt-note-pencil
    - ph-dt-number-circle-eight
    - ph-dt-number-circle-five
    - ph-dt-number-circle-four
    - ph-dt-number-circle-nine
    - ph-dt-number-circle-one
    - ph-dt-number-circle-seven
    - ph-dt-number-circle-six
    - ph-dt-number-circle-three
    - ph-dt-number-circle-two
    - ph-dt-number-circle-zero
    - ph-dt-number-square-eight
    - ph-dt-number-square-five
    - ph-dt-number-square-four
    - ph-dt-number-square-nine
    - ph-dt-number-square-one
    - ph-dt-number-square-seven
    - ph-dt-number-square-six
    - ph-dt-number-square-three
    - ph-dt-number-square-two
    - ph-dt-number-square-zero
    - ph-dt-paint-brush
    - ph-dt-palette
    - ph-dt-paperclip
    - ph-dt-paper-plane-tilt
    - ph-dt-pause
    - ph-dt-pen
    - ph-dt-pencil
    - ph-dt-pencil-line
    - ph-dt-phone-list
    - ph-dt-play
    - ph-dt-plug
    - ph-dt-plus
    - ph-dt-plus-circle
    - ph-dt-plus-square
    - ph-dt-power
    - ph-dt-presentation
    - ph-dt-prohibit
    - ph-dt-push-pin-simple
    - ph-dt-puzzle-piece
    - ph-dt-qr-code
    - ph-dt-question
    - ph-dt-quotes
    - ph-dt-radioactive
    - ph-dt-radio-button
    - ph-dt-reddit
    - ph-dt-rewind
    - ph-dt-robot
    - ph-dt-rocket
    - ph-dt-rows
    - ph-dt-seal
    - ph-dt-searxng
    - ph-dt-send
    - ph-dt-share
    - ph-dt-share-network
    - ph-dt-shield
    - ph-dt-shield-star
    - ph-dt-sidebar
    - ph-dt-signature
    - ph-dt-sign-in
    - ph-dt-sign-out
    - ph-dt-skip-back
    - ph-dt-skip-forward
    - ph-dt-sliders-horizontal
    - ph-dt-smile
    - ph-dt-smiley
    - ph-dt-smiley-nervous
    - ph-dt-sparkle
    - ph-dt-spinner
    - ph-dt-square
    - ph-dt-squares-four
    - ph-dt-stack
    - ph-dt-stamp
    - ph-dt-star
    - ph-dt-star-four
    - ph-dt-student
    - ph-dt-sun
    - ph-dt-tag
    - ph-dt-target
    - ph-dt-terminal
    - ph-dt-text
    - ph-dt-text-a
    - ph-dt-text-align-left
    - ph-dt-text-b
    - ph-dt-text-italic
    - ph-dt-thermometer
    - ph-dt-thumbs-down
    - ph-dt-thumbs-up
    - ph-dt-ticket
    - ph-dt-toggle-left
    - ph-dt-toggle-right
    - ph-dt-translate
    - ph-dt-trash
    - ph-dt-tray
    - ph-dt-tree-duotone
    - ph-dt-trophy
    - ph-dt-twitter-logo
    - ph-dt-ufo
    - ph-dt-upload
    - ph-dt-usd
    - ph-dt-user
    - ph-dt-user-circle-dashed
    - ph-dt-user-gear
    - ph-dt-user-minus
    - ph-dt-user-plus
    - ph-dt-users
    - ph-dt-users-three
    - ph-dt-video-camera
    - ph-dt-video-conference
    - ph-dt-videos
    - ph-dt-vote
    - ph-dt-wallet
    - ph-dt-warning
    - ph-dt-warning-circle
    - ph-dt-wikiless
    - ph-dt-windows-logo
    - ph-dt-wrench
    - ph-dt-x-circle
    - ph-dt-xmr
    - ph-dt-yin-yang
